# GitHub Actions: Compliance Check on PR
# Chạy Terraform plan, Checkov, và OPA policy checks

name: Compliance Check

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.6.0

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compliance-aws/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  checkov-scan:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: compliance-aws/terraform
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
          soft_fail: false
          download_external_modules: false

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: checkov-results.sarif

  opa-policy-check:
    name: OPA Policy Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compliance-aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend=false

      - name: Generate Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Test OPA Policies
        run: |
          opa test policies/rego/ -v

      - name: Run OPA Policy Check
        id: opa_check
        run: |
          cd terraform
          opa eval \
            --data ../policies/rego/security.rego \
            --input tfplan.json \
            --format pretty \
            'data.aws.compliance.deny' > opa-results.txt

          cat opa-results.txt

          # Check if có violations
          if grep -q "CRITICAL\|HIGH" opa-results.txt; then
            echo "❌ OPA policy violations found!"
            cat opa-results.txt
            exit 1
          else
            echo "✅ No critical OPA policy violations"
          fi

      - name: Upload OPA Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: opa-results
          path: compliance-aws/terraform/opa-results.txt

  conftest-check:
    name: Conftest Policy Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compliance-aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.46.0/conftest_0.46.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.46.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Conftest
        run: |
          conftest test terraform/*.tf \
            --policy policies/rego/ \
            --all-namespaces \
            --no-fail

  summary:
    name: Compliance Summary
    runs-on: ubuntu-latest
    needs: [terraform-validate, checkov-scan, opa-policy-check]
    if: always()

    steps:
      - name: Check Results
        run: |
          echo "## 🛡️ Compliance Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform Validate | ${{ needs.terraform-validate.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Checkov Scan | ${{ needs.checkov-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| OPA Policy Check | ${{ needs.opa-policy-check.result }} |" >> $GITHUB_STEP_SUMMARY

      - name: Fail if any check failed
        if: |
          needs.terraform-validate.result == 'failure' ||
          needs.checkov-scan.result == 'failure' ||
          needs.opa-policy-check.result == 'failure'
        run: |
          echo "❌ Compliance checks failed!"
          exit 1
