# GitHub Actions: Deploy to AWS
# Deploy Terraform infrastructure và Lambda functions

name: Deploy to AWS

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.6.0

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    defaults:
      run:
        working-directory: ./compliance-aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Package Lambda Functions
        run: |
          cd lambda

          # Package Scanner
          pip install -r requirements.txt -t scanner_package/
          cp scanner.py scanner_package/
          cd scanner_package
          zip -r ../scanner.zip .
          cd ..
          rm -rf scanner_package

          # Package Remediation
          pip install -r requirements.txt -t remediation_package/
          cp remediation.py remediation_package/
          cd remediation_package
          zip -r ../remediation.zip .
          cd ..
          rm -rf remediation_package

          ls -lh *.zip

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan \
            -var="environment=${{ github.event.inputs.environment || 'dev' }}" \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      - name: Get Outputs
        id: outputs
        run: |
          cd terraform
          echo "evidence_bucket=$(terraform output -raw evidence_bucket_name)" >> $GITHUB_OUTPUT
          echo "scanner_lambda=$(terraform output -raw scanner_lambda_arn)" >> $GITHUB_OUTPUT
          echo "remediation_lambda=$(terraform output -raw remediation_lambda_arn)" >> $GITHUB_OUTPUT

      - name: Test Lambda Scanner
        run: |
          aws lambda invoke \
            --function-name ${{ steps.outputs.outputs.scanner_lambda }} \
            --payload '{"scan_type":"manual"}' \
            response.json

          cat response.json

      - name: Deployment Summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Region:** ${{ env.AWS_REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Resources" >> $GITHUB_STEP_SUMMARY
          echo "- Evidence Bucket: \`${{ steps.outputs.outputs.evidence_bucket }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Scanner Lambda: \`${{ steps.outputs.outputs.scanner_lambda }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Remediation Lambda: \`${{ steps.outputs.outputs.remediation_lambda }}\`" >> $GITHUB_STEP_SUMMARY

  deploy-dashboard:
    name: Deploy Dashboard
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        working-directory: ./compliance-aws/dashboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Dashboard
        run: |
          python -c "import app; print('Dashboard app loaded successfully')"

      - name: Build Dashboard Info
        run: |
          echo "## 📊 Dashboard Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Dashboard files are ready for deployment." >> $GITHUB_STEP_SUMMARY
          echo "Run locally: \`python dashboard/app.py\`" >> $GITHUB_STEP_SUMMARY
